error: add test coverage for the file
The error declares couple struct/interface/methods which needed to be
tested as well, to validate the different output we would have by
calling them.