error: update the receiver and checkError method
The receiver for callErr did not need to be updated.

The checkError didn't need to be updated as both Err implement error, we
can keep this generic type to test other things.