error: Refactor error message to be meaningful
Refactoring of the error message of the Err and Errs types, in order to
provide meaningful details of the errors which have happened.

This changes make the test to pass again.